apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  clusterIP: None
  selector:
    app: {{ .Values.name }}-pod
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}

