services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
