services:
  ursh:
    image: notmde/urshsmth:35
    ports:
      - "5000:5000"
    environment:
      - APP_PORT=5000
      - REDIS_URI=redis://redis:6379
      - DEV_FLAG=1
    depends_on:
      - redis

  redis:
    image: redis:latest
