pipeline {
    agent {
        label "worker"
    }
    
    environment {
        DOCKER_HOST = 'tcp://192.168.122.42:4243'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/snwzt/url-shortener'
            }
        }

        stage('Initialize Docker') {
            steps {
                script {
                    def dockerHome = tool 'docker'
                    env.PATH = "${dockerHome}/bin:${env.PATH}"
                }
                withCredentials([usernamePassword(credentialsId: 'e301d761-0cdf-44de-bda6-a634432bc4b7', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
                }
            }
        }

        stage('Build and Push') {
            parallel {
                stage('Build and Push shorten') {
                    steps {
                        sh "docker build shorten -t urshsh:${env.BUILD_ID}"
                        sh "docker tag urshsh:${env.BUILD_ID} notmde/urshsh:${env.BUILD_ID}"
                        sh "docker push notmde/urshsh:${env.BUILD_ID}"
                    }
                }

                stage('Build and Push unshorten') {
                    steps {
                        sh "docker build unshorten -t urshunsh:${env.BUILD_ID}"
                        sh "docker tag urshunsh:${env.BUILD_ID} notmde/urshunsh:${env.BUILD_ID}"
                        sh "docker push notmde/urshunsh:${env.BUILD_ID}"
                    }
                }
            }
        }
    }
}