apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-dep
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-pod
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          env:
            - name: REDIS_URI
              value: "redis://{{ .Values.db.name }}-svc.{{ .Values.db.namespace }}.svc.cluster.local:{{ .Values.db.port }}"
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: APP_PORT
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always

