apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.name }}-pod
