apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ursh
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: app
        namespace: app
        helmOverrides: ''
      - name: db
        namespace: db
        helmOverrides: |
          nodeName: gort-instance-1
  template:
    metadata:
      name: '{{.name}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/snwzt/stuff
        path: 'urshsmth-helm/{{.name}}'
        targetRevision: HEAD
        helm:
          valueFiles:
          - values.yml
          values: '{{.helmOverrides}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
