---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.application }}-{{ .Values.db.name }}-pv
  annotations: {{ .Values.db.annotations | toYaml | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.db.volumeClaims.requests.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/disks/{{ .Values.db.name }}-data

